var sizeWeight = [
                      {"item": "Crewneck", 
                      "size": "Small",
                      "Variant Grams": 340}, 
                      {"item": "Crewneck", 
                      "size": "Medium",
                      "Variant Grams": 369}, 
                      {"item": "Crewneck", 
                      "size": "Large",
                      "Variant Grams": 397},
                      {"item": "Crewneck", 
                      "size": "XL",
                      "Variant Grams": 397},
                      {"item": "Crewneck", 
                      "size": "2XL",
                      "Variant Grams": 425},
                      {"item": "Crewneck", 
                      "size": "3XL",
                      "Variant Grams": 454},

                      {"item": "Hoodie", 
                      "size": "Small",
                      "Variant Grams": 340}, 
                      {"item": "Hoodie", 
                      "size": "Medium",
                      "Variant Grams": 369}, 
                      {"item": "Hoodie", 
                      "size": "Large",
                      "Variant Grams": 397},
                      {"item": "Hoodie", 
                      "size": "XL",
                      "Variant Grams": 397},
                      {"item": "Hoodie", 
                      "size": "2XL",
                      "Variant Grams": 425},
                      {"item": "Hoodie", 
                      "size": "3XL",
                      "Variant Grams": 454},

                      {"item": "Kid's Tee", 
                      "size": "Small",
                      "Variant Grams": 350}, 
                      {"item": "Kid's Tee", 
                      "size": "Medium",
                      "Variant Grams": 360}, 
                      {"item": "Kid's Tee", 
                      "size": "Large",
                      "Variant Grams": 570},
                      {"item": "Kid's Tee", 
                      "size": "XL",
                      "Variant Grams": 570},
                      {"item": "Kid's Tee", 
                      "size": "2XL",
                      "Variant Grams": 570},

                      {"item": "Onesie", 
                      "size": "Newborn",
                      "Variant Grams": 350}, 
                      {"item": "Onesie", 
                      "size": "6M",
                      "Variant Grams": 360}, 
                      {"item": "Onesie", 
                      "size": "12M",
                      "Variant Grams": 570},
                      {"item": "Onesie", 
                      "size": "18M",
                      "Variant Grams": 570},
                      {"item": "Onesie", 
                      "size": "24M",
                      "Variant Grams": 570},


                      {"item": "Tank Top", 
                      "size": "Small",
                      "Variant Grams": 113}, 
                      {"item": "Tank Top", 
                      "size": "Medium",
                      "Variant Grams": 142}, 
                      {"item": "Tank Top", 
                      "size": "Large",
                      "Variant Grams": 142},
                      {"item": "Tank Top", 
                      "size": "XL",
                      "Variant Grams": 170},
                      {"item": "Tank Top", 
                      "size": "2XL",
                      "Variant Grams": 198},

                      {"item": "Men's Tee", 
                      "size": "Small",
                      "Variant Grams": 142}, 
                      {"item": "Men's Tee", 
                      "size": "Medium",
                      "Variant Grams": 170}, 
                      {"item": "Men's Tee", 
                      "size": "Large",
                      "Variant Grams": 170},
                      {"item": "Men's Tee", 
                      "size": "XL",
                      "Variant Grams": 198},
                      {"item": "Men's Tee", 
                      "size": "2XL",
                      "Variant Grams": 227},
                      {"item": "Men's Tee", 
                      "size": "3XL",
                      "Variant Grams": 255},

                      {"item": "Men's V", 
                      "size": "Small",
                      "Variant Grams": 142}, 
                      {"item": "Men's V", 
                      "size": "Medium",
                      "Variant Grams": 170}, 
                      {"item": "Men's V", 
                      "size": "Large",
                      "Variant Grams": 170},
                      {"item": "Men's V", 
                      "size": "XL",
                      "Variant Grams": 198},
                      {"item": "Men's V", 
                      "size": "2XL",
                      "Variant Grams": 227},
                      {"item": "Men's V", 
                      "size": "3XL",
                      "Variant Grams": 255},

                      {"item": "Women's V", 
                      "size": "Small",
                      "Variant Grams": 113}, 
                      {"item": "Women's V", 
                      "size": "Medium",
                      "Variant Grams": 142}, 
                      {"item": "Women's V", 
                      "size": "Large",
                      "Variant Grams": 142},
                      {"item": "Women's V", 
                      "size": "XL",
                      "Variant Grams": 170},
                      {"item": "Women's V", 
                      "size": "2XL",
                      "Variant Grams": 198}
                      ]

module.exports = sizeWeight;