var sizeWeight = [
                      {"item": "Crewneck", 
                      "size": "Small",
                      "Variant Grams": 340}, 
                      {"item": "Crewneck", 
                      "size": "Medium",
                      "Variant Grams": 369}, 
                      {"item": "Crewneck", 
                      "size": "Large",
                      "Variant Grams": 397},
                      {"item": "Crewneck", 
                      "size": "XL",
                      "Variant Grams": 397},
                      {"item": "Crewneck", 
                      "size": "2XL",
                      "Variant Grams": 425},
                      {"item": "Crewneck", 
                      "size": "3XL",
                      "Variant Grams": 454},

                      {"item": "Hoodie", 
                      "size": "Small",
                      "Variant Grams": 340}, 
                      {"item": "Hoodie", 
                      "size": "Medium",
                      "Variant Grams": 369}, 
                      {"item": "Hoodie", 
                      "size": "Large",
                      "Variant Grams": 397},
                      {"item": "Hoodie", 
                      "size": "XL",
                      "Variant Grams": 397},
                      {"item": "Hoodie", 
                      "size": "2XL",
                      "Variant Grams": 425},
                      {"item": "Hoodie", 
                      "size": "3XL",
                      "Variant Grams": 454},

                      {"item": "Kid's Tee", 
                      "size": "Size 2",
                      "Variant Grams": 113}, 
                      {"item": "Kid's Tee", 
                      "size": "Size 3",
                      "Variant Grams": 142}, 
                      {"item": "Kid's Tee", 
                      "size": "Size 4",
                      "Variant Grams": 142},
                      {"item": "Kid's Tee", 
                      "size": "Size 5/6",
                      "Variant Grams": 170},
                      // {"item": "Kid's Tee", 
                      // "size": "2XL",
                      // "Variant Grams": 198},

                      {"item": "Onesie", 
                      "size": "Newborn",
                      "Variant Grams": 113}, 
                      {"item": "Onesie", 
                      "size": "6M",
                      "Variant Grams": 142}, 
                      {"item": "Onesie", 
                      "size": "12M",
                      "Variant Grams": 142},
                      {"item": "Onesie", 
                      "size": "18M",
                      "Variant Grams": 170},
                      {"item": "Onesie", 
                      "size": "24M",
                      "Variant Grams": 198},


                      {"item": "Tank Top", 
                      "size": "Small",
                      "Variant Grams": 113}, 
                      {"item": "Tank Top", 
                      "size": "Medium",
                      "Variant Grams": 142}, 
                      {"item": "Tank Top", 
                      "size": "Large",
                      "Variant Grams": 142},
                      {"item": "Tank Top", 
                      "size": "XL",
                      "Variant Grams": 170},
                      {"item": "Tank Top", 
                      "size": "2XL",
                      "Variant Grams": 198},

                      {"item": "Men's Tee", 
                      "size": "Small",
                      "Variant Grams": 142}, 
                      {"item": "Men's Tee", 
                      "size": "Medium",
                      "Variant Grams": 170}, 
                      {"item": "Men's Tee", 
                      "size": "Large",
                      "Variant Grams": 170},
                      {"item": "Men's Tee", 
                      "size": "XL",
                      "Variant Grams": 198},
                      {"item": "Men's Tee", 
                      "size": "2XL",
                      "Variant Grams": 227},
                      {"item": "Men's Tee", 
                      "size": "3XL",
                      "Variant Grams": 255},

                      {"item": "Men's V", 
                      "size": "Small",
                      "Variant Grams": 142}, 
                      {"item": "Men's V", 
                      "size": "Medium",
                      "Variant Grams": 170}, 
                      {"item": "Men's V", 
                      "size": "Large",
                      "Variant Grams": 170},
                      {"item": "Men's V", 
                      "size": "XL",
                      "Variant Grams": 198},
                      {"item": "Men's V", 
                      "size": "2XL",
                      "Variant Grams": 227},
                      {"item": "Men's V", 
                      "size": "3XL",
                      "Variant Grams": 255},

                      {"item": "Women's V", 
                      "size": "Small",
                      "Variant Grams": 113}, 
                      {"item": "Women's V", 
                      "size": "Medium",
                      "Variant Grams": 142}, 
                      {"item": "Women's V", 
                      "size": "Large",
                      "Variant Grams": 142},
                      {"item": "Women's V", 
                      "size": "XL",
                      "Variant Grams": 170},
                      {"item": "Women's V", 
                      "size": "2XL",
                      "Variant Grams": 198},

                      {"item": "Tote Bag", 
                      "size": "One-size",
                      "Variant Grams": 227},

                      {"item": "Mug", 
                      "size": "12oz",
                      "Variant Grams": 227},
                      {"item": "Mug", 
                      "size": "16oz",
                      "Variant Grams": 227},

                      {"item": "Poster", 
                      "size": "Small",
                      "Variant Grams": 100},
                      {"item": "Poster", 
                      "size": "Medium",
                      "Variant Grams": 100},
                      {"item": "Poster", 
                      "size": "Large",
                      "Variant Grams": 100}

                      ]

module.exports = sizeWeight;